version: '3.8'
services:
  app-subscriber:
    container_name: subscriber-webservice-app
    image: subscriber-webservice-app
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - pg
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg:5432/subscriberDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=subscriberDB
volumes:
  data: {}
